### ISSUE TITLE
Refactoring of fine-tuning code

### ISSUE THREAD

**Issue by jordiplanascuchi** [wri-dssg/policy-data-analyzer#64]

**Comment by jordiplanascuchi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactoring fine-tuning code](https://trello.com/c/WaEmXCUZ/90-refactoring-fine-tuning-code)

**Comment by ramanshsharma2806** [comment]
I think we have completed the refactoring for fine-tuning code now. New code lives in master branch here [``/tasks/fine_tuning_sbert/``](https://github.com/wri-dssg/policy-data-analyzer/tree/master/tasks/fine_tuning_sbert). The next step is seed optimization which is in a different branch.
